name: Bug 反馈
description: 程序异常、崩溃、无法使用
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: problem
    attributes:
      label: 问题描述
      description: 发生了什么？
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 复现步骤
      description: 怎么操作会出现这个问题？
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 日志或截图
      description: 可以粘贴日志、截图、报错信息