// 在开发机预编译，Worker 内不使用 eval / Function。
import Ajv from 'ajv/dist/2020.js';
import standaloneCode from 'ajv/dist/standalone/index.js';
import { readFileSync, writeFileSync } from 'node:fs';
const schema = JSON.parse(readFileSync(new URL('../../GPT_SoVITS/feedback/schema.json', import.meta.url)));
const ajv = new Ajv({ strict: false, allowUnionTypes: true, code: { source: true, lines: true } });
const validate = ajv.compile(schema);
writeFileSync(new URL('./src/schema-validator.cjs', import.meta.url), '// Generated by npm run generate; do not edit.\n' + standaloneCode(ajv, validate));
